### ISSUE TITLE
keychar always equals 65535

### ISSUE THREAD

**Issue by simonlovesyou** [WilixLead/iohook#1]
Whenever I use `iohook` to hook onto the keyboard keys, either on keyup or keydown, the value for key `keychar` in the event object is always 65535. I used Swedish keyboard at first but I tried with American as well with the same results.

I'm using `node 7.2.1` and `npm 3.10.10` on Macbook Pro 2015, macOS Sierra 10.12.1.

**Comment by WilixLead** [comment]
Hello!
Looks like it is libuiohook issue. I already test it in macOS Sierra and yes, it is really don't work. 
But in Ubuntu 16.04 it is working.
I leave this issue to libuiohook repository. Need to wait their decision.

Thank you

**Comment by WilixLead** [comment]
It just becourse "keychar" value come only in keypress event.
I remove this property from other keyboard events.

Thank you!
