### ISSUE TITLE
keydown events aren't passed correctly

### ISSUE THREAD

**Issue by harryshipton** [WilixLead/iohook#10]
System: Fedora 25
Node version: 6.10.2 (latest LTS)

I can't see where the problem is occurring at the moment, but keydown events aren't being handled correctly from what I can see. Instead of the keydown->keypress->keyup (4->3->5) events that should happen, I get keypress->keypress->keyup (3->3->5).

I enabled debugging, and also inserted the following line at the start of the `_handler` function in iohook's `index.js`:
```javascript
console.log(msg);
```

As an example when attempting to run with this modification in, pressing the a character on my keyboard gives an output of:
```
hook_event_proc [350]: Key 0X1E pressed. (0X61)
dispatch_event [117]: Dispatching event type 4.
hook_event_proc [382]: Key 0 typed. (a)
dispatch_event [117]: Dispatching event type 3.
a{ type: 3,
  mask: 8192,
  time: 16205,
  keyboard: { keychar: 97, keycode: 0, rawcode: 97 } }
{ type: 3,
  mask: 8192,
  time: 16205,
  keyboard: { keychar: 97, keycode: 0, rawcode: 97 } }
hook_event_proc [445]: Key 0X1E released. (0X61)
dispatch_event [117]: Dispatching event type 5.
{ type: 5,
  mask: 8192,
  time: 16245,
  keyboard: { keycode: 30, rawcode: 97 } }
```

I will very occasionally get a keydown event like I should be, but this is perhaps only 1% of the time.

**Comment by harryshipton** [comment]
It looks like the type changes from 4 to 3 whilst in `zqueue`, but again, I really don't know why.

**Comment by WilixLead** [comment]
Keypress not implemented at this moment. I get some problems with this event. Sometimes module just crash with this event. Looks like it happened only in latest MacOS, I leave issue in libuiohook, but don't receive any response.
Now you can see keydown -> keyup messages.

But if you mean something different, please explain

**Comment by harryshipton** [comment]
I'm running on Fedora, so I'm not sure if that's why we're getting different results.

It's the keydown (which is type 4) events which I'm not receiving. The library is sending keypress (type 3) events to me when I should be receiving a keydown (type 4) event.

I did some more testing, and found out that the event type changes from type 4 (keydown) to type 3 (keypress) whilst the event pointer has been added to the queue `zqueue`, so this isn't a bug with libuiohook, and I have a feeling it's therefore not the same bug that you're talking about.

I went as far as I could, but now I'm out of ideas on where to go next, as I believe something has a pointer to the event, and is modifying it after calling `Send()` on `AsyncProgressWorkerBase`.

It's a little confusing, so if there's anything else that you think I can write a little better, please don't hesitate to ask :)

**Comment by WilixLead** [comment]
Now I understand you. But looks like it happened only in Fedora like systems. Can you check in another system like ubuntu/centos/etc.? 
Because I check in Windows/MacOS/Ubuntu 16 and don't get this problem

**Comment by harryshipton** [comment]
Sure thing, I'll fire up a VM and see how that performs. I'll also try it on Windows (which is running directly on my computer).

I'll probably do that tomorrow though, as it's getting pretty late here.

**Comment by harryshipton** [comment]
I haven't had chance to setup another VM to test it in, but I did create a patch [here](https://github.com/harryshipton/iohook). Storing the type independently, in an int queue separate from the main zqueue fixed the problem for me, so I'll continue using that for now.

I understand that you're unlikely to implement this patch, since it seems specific to my system (or to Fedora), so I've had to change some of the links (e.g. for travis), so that I can use the patch in my personal application.

Hopefully I'll be able to find out what's actually going wrong soon, though.

**Comment by WilixLead** [comment]
Hm... I check your changes... And how you control ordering between queues?
I understand, both queues fills and clear in same time. But... I don't understand, what wrong with zqueue.

PS. While I write this answer, I think about link to event. May be problem with *event what I push to zqueue. I need make copy from link I think

**Comment by harryshipton** [comment]
zqueue stores a pointer to the event (rather than a copy of the event), so
other pieces of code can simply modify the type of the event if they have a
pointer to the event.

What I've done is store a copy of event->type (rather than a pointer to
it), so you'd have to modify the queue directly (as there's no pointer to
the int in the second queue). Therefore the type of the event is retained,
as no other code has access to it.

**Comment by WilixLead** [comment]
Yes. But in your case, other information about event can be changed asynchronously and you get right event type but wrong event data. I think, in your case, all fine. But in another, you can get type from keypress, but other data can have mouse movement info for example.
I want make full copy of whole event object in next update. It can help to solve some other problems I think.
Thank you! Your issue can help with solving another bugs :)
