### ISSUE TITLE
How to build for the electron 3.0.6?

### ISSUE THREAD

**Issue by rhymedys** [WilixLead/iohook#105]
I have a project made by electron 3.0.6 and node 8.x,but iohook is not support for electron 3.0.6. I need a help to tell me how to complie the project to support electron 3.0.6 or some other methods to make this project to support  electron 3.0.6. if you need some help , i will do my best to help you , thanks.

**Comment by Djiit** [comment]
Hi there, I'm currently uploading v0.2.1 with electron 3.0 compat ! Stay tuned.

**Comment by alexgreenland** [comment]
Hi,

Appreciate the quick turnaround earlier, thanks.

I just installed v0.2.1 and it doesn't run for me. The build works but running in Electron v3.0.6 causes it to bail out.

`dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScope12CreateHandleEPNS_8internal10HeapObjectEPNS1_6ObjectE`

`Referenced from: node_modules/segfault-handler/build/Release/segfault-handler.node`

`Expected in: flat namespace`

Node: v10.12.0
NPM: v6.4.1
Electron: v3.0.6
iohook: v0.2.1

**Comment by Djiit** [comment]
Could you try with node 9? Not sure if node 10 is really working now...

**Comment by Djiit** [comment]
(I'm running on 3.0.6 on my machine)

**Comment by alexgreenland** [comment]
I'm afraid we can't really. We were on Node LTS (v8) which was fine for osx-mouse, but we need to move to v10 to get a feature only released in v10. On 30 October v10 will become the LTS version of Node so will be the standard.

Do you know what would be required to support v10?

**Comment by alexgreenland** [comment]
Just saw https://github.com/ddopson/node-segfault-handler/issues/51

I just cloned iohook and noted the dep of "segfault-handler": "^1.0.0". This should be enough to get 1.0.1, but it obviously wasn't getting it — when I tried to build it complained about v8-debug.h not found. When I changed it to "^1.0.1" I was able to build — looks promising.

Could you make that change please?

**Comment by Djiit** [comment]
@alexgreenland i'll look into that this afternoon. Thanks.

**Comment by Djiit** [comment]
@alexgreenland Hi, i'm closing this issue and opening another one about node10
