### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by Kraysh** [WilixLead/iohook#117]
## Current Behavior
![download 1](https://user-images.githubusercontent.com/31409782/47876775-e6496e00-ddf8-11e8-88cf-5013f0d28cab.png)

## Steps to Reproduce (for bugs)
1. `npm install iohook --save` and `npm install electron@2.0.13 --save`
2. Create main.js:
```
const { BrowserWindow, app } = require('electron')
const iohook = require('iohook')

app.on('ready', () => {
	mainWindow = new BrowserWindow();
});
```
3. Configure package.json:
```
"scripts": {
    "start": "electron ."
  }
```
4. Run  `npm start`

## Your Environment
* Version used: 0.2.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 8.12.0
* Electron version: 2.13.0
* Operating System and version (desktop or mobile): Windows 7

**Comment by Djiit** [comment]
Hello ! Did you add the "iohook" key in your package.json ?

**Comment by Djiit** [comment]
Be sure to follow the doc, you are missing an important part of the
configuration ;)

--
Julien

**Comment by Kraysh** [comment]
Oh, now working fine, but I made that mistake because in this link: [https://github.com/WilixLead/iohook/tree/master/examples/electron-example](url)
Does not say anything about it.
Thank you anyway

**Comment by Djiit** [comment]
Good to know, we will update this example ! Thanks !

--
Julien
