### ISSUE TITLE
Ability to ask iohook to look at rawCode instead of keyCode

### ISSUE THREAD

**Issue by anoadragon453** [WilixLead/iohook#121]
When trying to create an electron application that uses [mousetrap](https://craig.is/killing/mice) to record shortcuts and then iohook to listen for them globally, I've run into a bit of a snag. 

As noted at the end of [this comment](https://github.com/WilixLead/iohook/issues/74#issuecomment-435678359) I've noticed that the keycodes produced by mousetrap align with the `rawcode` value that iohook receives on a keypress. However, iohook uses the `keycode` value instead, as seen [here](https://github.com/WilixLead/iohook/blob/e88a10de4db6bbd3c486d3b8202f923afa38aada/index.js#L307).

Ideally then, it would be possible to add an optional parameter when starting iohook to choose to either listen on `keycode` or `rawcode` (I assume nobody would ever want both). This would preserve backwards compatibility while also providing more functionality.

If nobody has any major objections then I'm happy to make a PR for this soon.

**Comment by Djiit** [comment]
I get the idea ! Let's make "keycode" the default option, and allow "rawcode" for your usage. I'll be happy to merge this PR.
