### ISSUE TITLE
Can't find module

### ISSUE THREAD

**Issue by Venryx** [WilixLead/iohook#16]
I'm getting this error when attempting to use the library in a Node program:
```
C:\Root\Apps\Control\@V\RobotJS\Scripts>node Dist/Main.js
Loading native binary: C:\Root\Apps\Control\@V\RobotJS\Scripts\node_modules\iohook\builds\node-v48-win32-x64\build\Release\iohook.node
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Root\Apps\Control\@V\RobotJS\Scripts\node_modules\iohook\builds\node-v48-win32-x64\build\Release\iohook.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Root\Apps\Control\@V\RobotJS\Scripts\node_modules\iohook\index.js:16:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

The file, however, does exist: I copied the path above exactly, into Windows explorer, and it opened the file.

I did a search, and found a similar error message here: http://stackoverflow.com/questions/41253450/error-the-specified-module-could-not-be-found

They suggested to use the [Dependeny Walker](http://www.dependencywalker.com/) program to see if it was trying to use a dll that was missing. (as that can be the cause of the error)

I did so, and saw this:
![](http://i.imgur.com/uqTvxJ2.png)

So, it seems that the "libuiohook.dll" file is missing.

But why? I'm not sure how to fix it, as running "npm run build" myself errors, and I can't find a prebuilt copy of the "libuiohook.dll" file.

**Comment by soyFerrero** [comment]
The same problem.. @Venryx  Some advance?

**Comment by Venryx** [comment]
@soyFerrero I didn't figure out how to fix it, so I'm just using a different module for global hooks for now: https://github.com/tomzx/gkm

There are some others listed here, if that one doesn't work for you: https://github.com/octalmage/robotjs/wiki/Plugins-(or-compatible-modules)

**Comment by soyFerrero** [comment]
@Venryx Thank u so much. I'm going to try it

**Comment by Toinane** [comment]
The same for me on Windows 10 :/ I have the same issue..

**Comment by WilixLead** [comment]
You need recompile iohook for windows. At this moment I can't configure appveyor for normal automated compiling for windows :( 
But I try to do in in virtual machine with windows today

**Comment by thomsa** [comment]
Hey, I have the same problem with this config file
```
"iohook": {
    "targets": [
      "node-59",
      "electron-54",
      "electron-57",
      "electron-64"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
```
The actual one it's trying to import is the 64
`\builds\electron-v64-win32-x64\build\Release\iohook.node`
It doesn't work, "specified module could not be found"

Any ideas?

**Comment by Djiit** [comment]
Hi @thomsa , could you please open a new ticket using our template ? Thanks !
