### ISSUE TITLE
Keycodes don't match

### ISSUE THREAD

**Issue by PedroEsperanca** [WilixLead/iohook#18]
They don't match :
- on different listener events
- with keys from the browser

If you tell me a way to go about fixing this correctly I might be able to help.

**Comment by samybob1** [comment]
[In the README](https://github.com/WilixLead/iohook/blob/master/README.md#keydown), when you press "d" the keycode is 46:
`{ keychar: 'd', keycode: 46, rawcode: 8, type: 'keydown' }`

When I press "d", the keycode I get is 32:
`{ keycode: 32, rawcode: 2, type: 'keydown' }`

Why? How can I convert a keycode or a rawcode to a char? Here is the values I have: (KC for keycode, RC for rawcode)

```
# KC RC
a 16 12
b 48 11
c 46 8
d 32 2
e 18 14
f 33 3
g 34 5
h 35 4
i 23 34
j 36 38
k 37 40
l 38 37
m 39 41
n 49 45
o 24 31
p 25 35
q 30 0
r 19 15
s 31 1
t 20 17
u 22 32
v 47 9
w 44 6
x 45 7
y 21 16
z 17 13
```

Thanks!

**Comment by WilixLead** [comment]
This data generate [libuiohook](https://github.com/kwhat/libuiohook) try ask this question in this repo. 
I don't control this data in my module. I think, it relate by OS and locale settings.

PS. [This is](https://github.com/kwhat/libuiohook/blob/master/include/uiohook.h) key definition. Try research this file. May be it help you.

**Comment by solderzzc** [comment]
libuiohook is using **Key Number** of [Linux Keycode Table](http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlkeycodes.html)

**Comment by WilixLead** [comment]
In future I plan add matching table for different OS's in node.js side.
If anybody what to help me, pull-request welcome :)
