### ISSUE TITLE
0.1.9 not available through npm

### ISSUE THREAD

**Issue by bence-nagy** [WilixLead/iohook#19]
I'm trying to use this package in an electron app on OSX 10.12.3, and version 0.1.8 seems to have some problems (mouseclick event fired twice, keydown only firing for special buttons, like `Command`, `Alt`, etc, but not for _regular_ ones, like letters). These problems are all fixed if I replace the binary with the 0.1.9 version, but that version is not available through npm.

Could you please publish that version to npm?

Thanks in advance.

**Comment by WilixLead** [comment]
Now available. You can try to use it

**Comment by bence-nagy** [comment]
Thanks a lot, it is available now, I just installed it with npm, and it works as it should. Thanks again.
