### ISSUE TITLE
keypress doesn't fire any events

### ISSUE THREAD

**Issue by simonlovesyou** [WilixLead/iohook#2]
`keypress` doesn't seem to fire any events, `keyup` and `keydown` works though.

**Comment by WilixLead** [comment]
Hello!
Looks like it is libuiohook issue. I already test it in macOS Sierra and yes, it is really don't work.
But in Ubuntu 16.04 it is working.
I leave this issue to libuiohook repository. Need to wait their decision.

Thank you
