### ISSUE TITLE
Node.js v8* ABI 57

### ISSUE THREAD

**Issue by dimapaloskin** [WilixLead/iohook#23]
Hello!

If it possible, can you build release with new node (v8* with ABI 57) supports?
Or just provide some manual how I can do it myself.

Currently no idea how I can do it :)

**Comment by WilixLead** [comment]
You can compile this module. It should be pretty simple, but require some additional packages in system.
[Try this](https://github.com/WilixLead/iohook#manual-compilation-for-your-version-of-environment)
 When I get additional time, I try add prebuilt version to package

**Comment by dimapaloskin** [comment]
Awesome! :)

**Comment by rakshithravi1997** [comment]
Eagerly waiting on the prebuilt version for node-57. I'm having issues compiling it myself. Any idea when it would be available please?

**Comment by WilixLead** [comment]
Please use latest build
