### ISSUE TITLE
How to use this without the prebuild?

### ISSUE THREAD

**Issue by willemkokke** [WilixLead/iohook#24]
Hi, I'm trying to use this on macOS 10.12 (Sierra) with Electron 1.7.5, for which there is no prebuilt package available.

I've managed to compile it following the instructions in the readme (running npm run build) and this produces a module in  iohook/build/Release/iohook.node.

This causes errors when trying to use it because the native module is expected to be in iohook/builds/electron-v54-darwin-x64/build/Release/iohook.node

I can of course manually move this file to where it is inpected, but an important goal is to have the app up and running straight away after a clean checkout and npm install.

Am I missing something or is this module only meant to work with  prebuilt binaries? 

Adding support for electron abi 54 appears trivial, it just needs a few lines added in support.js. If I do that, running `npm run deploy` produces iohook/prebuilds/iohook-v0.1.9-electron-v54-darwin-x64.tar.gz.

Am I correct that that is all that's required? I'd be happy to send a pull request in that case.

**Comment by gavinmcdermott** [comment]
@willemkokke - did you end up finding a solution that worked for you on this one?

**Comment by WilixLead** [comment]
@willemkokke Sorry for long response. Make pull-request if you can. 
If not. I try to do it in short time.
