### ISSUE TITLE
Mousemove event doesn't work on debian

### ISSUE THREAD

**Issue by Toinane** [WilixLead/iohook#26]
Hey there!
First of all, I really appreciate your work :)
For my project, I want to catch the mousemove event, I haven't any log when I use it from my Debian 9.
I use Electron 1.6.2 & prebuilt for Electron 53 (all platform & x64)

When I activate debug mode, I have this : 

```
hook_event_proc [782]: Mouse dragged to 310, 729. (0X2000)
dispatch_event [117]: Dispatching event type 10.
hook_event_proc [782]: Mouse dragged to 310, 728. (0X2000)
dispatch_event [117]: Dispatching event type 10.
hook_event_proc [782]: Mouse dragged to 310, 729. (0X2000)
dispatch_event [117]: Dispatching event type 10.
hook_event_proc [782]: Mouse dragged to 311, 730. (0X2000)
dispatch_event [117]: Dispatching event type 10.
```

I don't understand why I have this logs but not from the JS hook :/

```
ioHook.on("mousemove", event => {
    console.log(event)
  })
```

but others events works

**Comment by Toinane** [comment]
So I look up more in the code, and I found the event type 10 is "mousedrag", so I've tested mousedrag and it's work finally :)

**Comment by Djiit** [comment]
Should we close this issue ?

**Comment by WilixLead** [comment]
`mousedrag` should be called when you click to mouse button and move the mouse.
`mousemove` called when you move mouse without touching buttons

**Comment by Toinane** [comment]
Yes, when I wrote that issue, it didn't work. But the mousedrag was a workaround.
I haven't tried again since.

**Comment by Djiit** [comment]
FWIW I can reproduce it with Electron 1.7.10 (ABI 54) and iohook 0.1.13).

**Comment by matthewshirley** [comment]
Is this resolved after updating libuiohook to 1.1?

**Comment by Djiit** [comment]
@Toinane any news on this ? Should we close this ticket ? Thanks !

**Comment by Toinane** [comment]
I will check this afterwork on Debian @Djiit :)
Otherwise I've tested on macOS and it's work.

**Comment by Toinane** [comment]
Yep It work on my debian :) Thank's!
We can close this ticket!

**Comment by Djiit** [comment]
Thanks for your feedback, awesome !
