### ISSUE TITLE
listen to 4 keyboards and distinguish between them

### ISSUE THREAD

**Issue by philippschwemberger** [WilixLead/iohook#28]
Hi!
Thanks for this cool library. 
I would love to use it in a project where i want to listen to 4 keyboards attached to a raspberry pi 3 and i have to be able to tell which keyboard caused which input.

I have already tried it with this library https://github.com/song940/input-event where i can specify the input device path like this `const input = new InputEvent('/dev/input/event0');`
Like this I am able to distinguish between different input paths. Unfortunately this library doesn't work with more than 2 keyboards. 

So I thought to give it a shot with your library, but I couldn't find any place where I could specify the device path like that.

Would this be possible with your library?

Thanks,
Philipp

**Comment by WilixLead** [comment]
Hello! This module capture global keys and not only from one device. So module don't support device choice.
But, if you need open UNIX like devices for reading, you can find another modules for this.
Like [node-hid](https://github.com/node-hid/node-hid) or [node-linux-input-device](https://github.com/athombv/node-linux-input-device)
