### ISSUE TITLE
Doesn't work on Windows 10 x64

### ISSUE THREAD

**Issue by BlazingFire007** [WilixLead/iohook#29]
Using this code:
```js
const ioHook = require('iohook');
 
ioHook.on("mousemove", event => {
  console.log(event);
});
 
ioHook.start();
```
I get this error:
```js
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Eli\Desktop\!NODEJS\node_modules\iohook\builds\node-v51-win32-x64\build\Release\iohook.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Eli\Desktop\!NODEJS\node_modules\iohook\index.js:16:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by Djiit** [comment]
Hi there, could you please specify your node/npm/yarn version so we can help ?

**Comment by BlazingFire007** [comment]
@Djiit Node 7.7.4 NPM 4.1.2

**Comment by Earl-Brown** [comment]
I'm getting the same issue with NPM 4.0.5 and node 7.4.0.  The file exists, so I'm guessing there's probably a load issue.  Perhaps it's compiled for 32-bit and the attempt is to load it into a 64-bit OS?

**Comment by xobotyi** [comment]
Same stuff.

Node: 8.6.0

During build had one warning:
`"C:\Users\a.zinoviev\Desktop\iohook-master\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (1) ->
"C:\Users\a.zinoviev\Desktop\iohook-master\build\iohook.vcxproj" (целевой объект по умолчанию) (8) ->
(Целевой объект ClCompile) ->
  C:\Users\a.zinoviev\.cmake-js\node-x64\v8.6.0\include\node\node.h(625): warning C4251: 'node::CallbackScope::try_catch_': class 'v8::TryCatch' needs to have dll-interface to be used by clients of class 'node::
CallbackScope' [C:\Users\a.zinoviev\Desktop\iohook-master\build\iohook.vcxproj]

    Предупреждений: 1
    Ошибок: 0`

**Comment by xobotyi** [comment]
Quick solution:
Sut the uiohook.dll near the iohook.node file. Solved problem for me

**Comment by Earl-Brown** [comment]
Where do I find uiohook.dll?

**Comment by xobotyi** [comment]
@Earl-Brown in the build directory. i'm building iohook on my own for Windows.

**Comment by Earl-Brown** [comment]
Ah...do you have instructions for doing that?  I didn't see any in the readme.

**Comment by xobotyi** [comment]
I'm going to iohook/libuiohook dir and making there over MinGW:
> ./bootstrap.sh
> ./configure
> make && make install
then going to iohook dir and makeing over default Windows cmd:
> cmake-js rebuild -r="electron" -v="1.7.9" -a="x64"
buld will be at iohook/build/Release directory

**Comment by Earl-Brown** [comment]
I'll have to try that.  Probably take a while because of setup stuff.  Do you think that would build for Node 8+?

**Comment by tobeorla** [comment]
@Earl-Brown did you succeed? could you share the resulting .dll?

**Comment by Djiit** [comment]
Hi @Earl-Brown , could you elaborate on the alternative you found ?

Thanks !
