### ISSUE TITLE
Installation variant ?

### ISSUE THREAD

**Issue by Djiit** [WilixLead/iohook#3]
Hi there, 

On macOS 10.12.2, , I had to use the following command to install `automake` with brew instead of `autoreconf`. Don't know if it's specific to the platform.

**Comment by WilixLead** [comment]
Unfortunately I am not sure which version is more faithful. I just find the installation instructions for my OS version on the Internet.
In your system compilation working with installed packages?

**Comment by WilixLead** [comment]
Closing while no new information provided. Not an issue
