### ISSUE TITLE
Update targets to electron 57

### ISSUE THREAD

**Issue by natew** [WilixLead/iohook#38]
Just a small request to add this enable updating.

**Comment by WilixLead** [comment]
Please say what is version of electron use 57 abi? 
I just cant find something like this https://nodejs.org/en/download/releases/ but for electron.

Also, you can make pull request with updated `package.json`. All what you need, place your electron version after last version in json array

**Comment by Djiit** [comment]
Hi there, 

You can have a look at the https://github.com/lgeiger/electron-abi repo but unfortunately it seems outdated.

57 is for **1.8.X** electron versions

**Comment by Djiit** [comment]
PR #44 might help on this. @WilixLead would you mind having a look ?

**Comment by WilixLead** [comment]
Merged. Thank you!

**Comment by ljubic** [comment]
Any plans for updating targets for electron ABI 64 version? :)
