### ISSUE TITLE
stop() not working in electron-v51-linux-x64

### ISSUE THREAD

**Issue by abhishekgargg** [WilixLead/iohook#41]
stop() is not stopping the eventlisteners or iohook. I'm using latest version of iohook, 0.1.12.
I tried it on a couple of other versions as well like 0.1.9 and the same problem was there as well.
and unload() is exiting my process, so as soon as i unload iohook, my application exits.

Can you please suggest a way in which i can stop iohook once started?

**Comment by WilixLead** [comment]
Please say, what you use? .on or .registerShortcut ?

**Comment by abhishekgargg** [comment]
I am using .on
Here is how I'm using it.
`const ioHook = require('iohook');
ioHook.start(true);
ioHook.on('mousedown', function(msg){console.log(msg)});
setTimeout(function(){ioHook.stop();},5000);
`

The same piece of code works for node-v51-linux-x64, but isn't working for electron-v51-linux-x64.
Please let me know if any other information is required on this issue.

**Comment by WilixLead** [comment]
Please try use your app with electron-v51-linux-x64 in another linux machine. Looks like it is related to OS or current build
