### ISSUE TITLE
module fails on Virtual machines and remote PCs

### ISSUE THREAD

**Issue by jlsilva1994** [WilixLead/iohook#47]
when running iohook in a Virtual box windows 7 machine, or in a microsoft azure remote machine with windows 10, the module fails with the following error:

PID 1056 received SIGSEGV for address: 0xfd11a06d
SymInit: Symbol-SearchPath: '.;C:\Users\jose luis\projects\desktopapp-prototype;                   C:\Users\myname\projects\desktopapp-prototype\node_modules\electron\dist;C:\W                   indows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/                   symbols;', symOptions: 530, UserName: 'my name'
OS-Version: 6.1.7601 (Service Pack 1) 0x100-0x1
c:\users\myname\projects\desktopapp-prototype\node_modules\segfault-handler\s                   rc\stackwalker.cpp (941): StackWalker::ShowCallstack
c:\users\myname\projects\desktopapp-prototype\node_modules\segfault-handler\s                   rc\segfault-handler.cpp (116): segfault_handler
00000000773B984B (ntdll): (filename not available): vsprintf_s
00000000773B8162 (ntdll): (filename not available): RtlUnwindEx
00000000773B8AC8 (ntdll): (filename not available): RtlRaiseException
000007FEFD11A06D (KERNELBASE): (filename not available): RaiseException
000007FEFD6E5113 (RPCRT4): (filename not available): RpcRaiseException
000007FEFD6E5893 (RPCRT4): (filename not available): RpcEpResolveBinding
000007FEFD71817F (RPCRT4): (filename not available): RpcAsyncRegisterInfo
000007FEFD7AC6FA (RPCRT4): (filename not available): Ndr64AsyncClientCall
000007FEFD7AC9BB (RPCRT4): (filename not available): Ndr64AsyncClientCall
000007FEFD7ACDE5 (RPCRT4): (filename not available): NdrClientCall3
000007FEF5971A04 (wlanapi): (filename not available): WlanOpenHandle
0000000141090A36 (electron): (filename not available): IsSandboxedProcess
0000000141090FD0 (electron): (filename not available): IsSandboxedProcess
000000014115FAD1 (electron): (filename not available): IsSandboxedProcess
000000014115FA00 (electron): (filename not available): IsSandboxedProcess
00000001410C8F20 (electron): (filename not available): IsSandboxedProcess
0000000141013188 (electron): (filename not available): IsSandboxedProcess
000000013FC7614B (electron): (filename not available): (function-name not available)
00000001404B30F0 (electron): (filename not available): IsSandboxedProcess
000000014018EFD5 (electron): (filename not available): IsSandboxedProcess
000000013FD5E96C (electron): (filename not available): GetHandleVerifier
000000013FD01836 (electron): (filename not available): GetHandleVerifier
000000013FD00320 (electron): (filename not available): GetHandleVerifier
000000013FD5FA17 (electron): (filename not available): GetHandleVerifier
000000013FD60304 (electron): (filename not available): GetHandleVerifier
000000013FCFD29E (electron): (filename not available): GetHandleVerifier
000000013FDC9B12 (electron): (filename not available): GetHandleVerifier
000000013FDCA629 (electron): (filename not available): GetHandleVerifier
000000013FCE08FB (electron): (filename not available): GetHandleVerifier
000000013FCE29B5 (electron): (filename not available): GetHandleVerifier
00000000772959BD (kernel32): (filename not available): BaseThreadInitThunk
00000000773CA2E1 (ntdll): (filename not available): RtlUserThreadStart
refresh_locale_list [470]: GetKeyboardLayoutList(0, NULL) found 2 layouts.
refresh_locale_list [487]: Received 2 locales.
load_input_helper [860]: refresh_locale_list() found 0 locale(s).
refresh_locale_list [628]: Could not find keyboard map for locale 00000000081608                   16!
refresh_locale_list [628]: Could not find keyboard map for locale 00000000040904                   09!

Im running it with electron 1.7.0

can you help me with this problem?

**Comment by senro** [comment]
me too!, but in normal win10!

**Comment by Djiit** [comment]
Hi there ! Could you please open a new issue so we can help you on this ?
