### ISSUE TITLE
More installation details for windows

### ISSUE THREAD

**Issue by comod** [WilixLead/iohook#48]
> Install: msys2 with autotools, pkg-config, libtool, gcc, clang, glib, C++ Build Tools, cmake

I cant or dont know how to install: "autotools" (do you mean automake?),  "C++ Build Tools" (?)

currently i failed with "OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.", which seems to be an cmake error.

Further more the example.js is already working! 
so, do I even have to compile that anymore? Actual my electron app cant find the module. The error here is:

Uncaught Error: Cannot find module 'C:\xampp\htdocs\electron-test\node_modules\iohook\builds\electron-v57-win32-x64\build\Release\iohook.node'
    at Module._resolveFilename

**Comment by jlsilva1994** [comment]
you could try this in your git bash:

npm install --global --production windows-build-tools

this command will install and configure for you all the tools that you need to build your electron application on windows. that command take a while, depending on your internet connection.
i also was having problems with instalation on windows, but that solved my problem.

**Comment by comod** [comment]
weirdly I had tried that before, but now it worked. but now I get this error:

CMake Error at CMakeLists.txt:19 (add_subdirectory):
  add_subdirectory given source "libuiohook" which is not an existing
  directory.

**Comment by comod** [comment]
ive deleted iohook and start over:

`npm install iohook --save`

C:\xampp\htdocs\electron-test\node_modules\iohook\install.js:14
  throw err;
  ^
 Prebuild for current platform (iohook-v0.1.13-node-v51-linux-ia32) not found!
 [            ......] - install: info lifecycle iohook@0.1.13~install: Failed to
npm WARN my-project@0.0.0 No repository field.
npm WARN my-project@0.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.1.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iohook@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\timo\AppData\Roaming\npm-cache\_logs\2018-03-03T09_44_18_5
00Z-debug.log

...ignore the error and tried the following...

```
cd node_modules/iohook
npm run build
```

 OKAY  take it away `electron-builder`

  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\electron-builder.yaml
Error: Unresolved node modules: iohook
    at C:\xampp\htdocs\electron-test\node_modules\electron-builder-lib\src\util\packageDependencies.ts:109:19
From previous event:
    at Collector.resolveUnresolvedHoisted (C:\xampp\htdocs\electron-test\node_modules\electron-builder-lib\out\util\packag
eDependencies.js:206:11)


... under which node in package.josn do i need to put exactly the

```
"iohook": {
  "targets": [
    "node-51",
    "electron-53"
  ],
  "platforms": [
    "win32",
    "darwin",
    "linux"
  ],
  "arches": [
    "x64",
    "ia32"
  ]
}
```

in root-node? in the build-node?

**Comment by comod** [comment]
i think i have been able to build it succesfully now (because the standalone xample.ks works). but i can't include to my electron app....

**Comment by Djiit** [comment]
Hi there, 

This is related to : https://github.com/WilixLead/iohook/issues/43

Edit your "root" package.json and reinstall your dependencis INCLUDING electron to ensure you have the correct electron version (53 = 1.8.X if I remember correctly). You can avoid the error about the linux-ia32 by dropping the linux line as in : 
```

"iohook": {
  "targets": [
    "node-51",
    "electron-53"
  ],
  "platforms": [
    "win32",
    "darwin",
  ],
  "arches": [
    "x64",
    "ia32"
  ]
}
```
I guess you are using electron+vuejs ? I'm on the same platform. Tell me if it fixes anything.

**Comment by comod** [comment]
It is working now! 

fixate electron verison to 
`"electron": "1.6.0",`

and copied prebuild hard from here https://github.com/vespakoen/iohook/releases/tag/v0.1.3

Thank you!

**Comment by Djiit** [comment]
Closing this for now :)
