### ISSUE TITLE
(doc) Create and host documentation

### ISSUE THREAD

**Issue by Djiit** [WilixLead/iohook#50]
We should provide users with a complete and sober documentation hosted on, e.g. Github Pages.

- [ ] Extract doc from readme
- [ ] Use a quick template from GitHub pages
- [ ] Setup the hosting

**Comment by Djiit** [comment]
Hi @DCzajkowski , it's online at : https://wilixlead.github.io/iohook/
Many thanks for your work !

**Comment by DCzajkowski** [comment]
Awesome 🎉
