### ISSUE TITLE
Uncaught Error: The Specified Module could not be found.

### ISSUE THREAD

**Issue by pihey12** [WilixLead/iohook#56]
When I package my electron app with asar settings, this error displayed when the app starts.

## Expected Behavior

Package the electron app with asar and iohook still run.

## Current Behavior

When I Package the electron app with asar to false, the Iohook still working. But when the asar set to true, the iohook could not be found.

The following error displayed:
> Uncaught Error: The specified module could not be found.
> \\?\C:\Users\Username\AppData\Local\Temp\452039c0-693f-4caf-99a7-393dc8f16557.tmp.node
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
>     at Object.Module._extensions..node (module.js:598:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Users\Username\Documents\TESTAPP\SOURCE CODE\release-builds\hirebrostimetracker-win32-x64\resources\app.asar\node_modules\iohook\index.js:17:21)
>     at Object.<anonymous> (C:\Users\Username\Documents\TESTAPP\SOURCE CODE\release-builds\hirebrostimetracker-win32-x64\resources\app.asar\node_modules\iohook\index.js:189:3)

Is there another way build package with asar and iohook?

## Possible Solution

Don't have yet any solution

## Steps to Reproduce (for bugs)

1. Build Package of Electron App using Electron Packager.
2. Set Asar to true.
3. Open App then in the console logs shows the error.

## Context

I want to compile all the resources of my electron app

## Your Environment

* Version used: 1.8.4
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js v8.9.4
* Operating System and version (desktop or mobile): Windows x64 and MacOS High Sierra
* Link to your project: private repo

**Comment by Djiit** [comment]
Hi there, We're happy to help :) Could you please edit your ticket to fit in our template ? It helps us diagnose your problem.

**Comment by pihey12** [comment]
@Djiit  Ok sir, I updated again the issue thanks

**Comment by Djiit** [comment]
Does the packaging without ASAR work ?
Did you put the correct ABI version in your package.json ?

**Comment by pihey12** [comment]
@Djiit yes I input the correct ABI version in package.json, my applications works when the asar set to false.

**Comment by Djiit** [comment]
Could you give us a link to your project OR a minimal project reproducing your error ? My main project using iohook is packaged in ASAR mode by electron-builder and everything is working great so far.

**Comment by Djiit** [comment]
Hi there,

I'm closing this as this is old now. Feel free to ping me here if you have any further informations.

**Comment by karacas** [comment]
@pihey12 
Maybe this help:
[https://github.com/wilix-team/iohook/issues/160](url)

**Comment by vahagnsargsian** [comment]
Hello, exactly same problem here. Please provide some solution to this.

**Comment by vahagnsargsian** [comment]
`<a href="https://imgur.com/j0eZlze"><img src="https://i.imgur.com/j0eZlze.png" title="source: imgur.com" /></a>`

**Comment by Antheso** [comment]
@Djiit The same problem
![image](https://user-images.githubusercontent.com/41594114/69793964-11f08080-11d2-11ea-888a-b49989780879.png)

**Comment by Antheso** [comment]
@vahagnsargsian try to update Visual C++ https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads. It should help

**Comment by hainguyents13** [comment]
is this problem fixed? I'm still facing this in some client PCs using windows 10, not all but some of them

**Comment by Maidomax** [comment]
Me too, still the same problem on some Windows 10 PCs

**Comment by AndreyTkachIT** [comment]
I have too this problem on some Windows 10 PCs

**Comment by vahagnsargsian** [comment]
still having same problem on some windows pc-s, now with electron 9 and iohook 0.6.6
its just giving "Specified module not found", trying to find iohook node which is there...

**Comment by marcelblum** [comment]
Typically when asar is set to true, native node modules like iohook must be excluded from the asar via the `"asar": {"unpack": ...}` build setting. Did you include that in your package.json?

**Comment by joineroff** [comment]
Just add msvcp140.dll and vcruntime140.dll to your app root. If you use electron-builder use "extraFiles"

`"extraFiles": [
      {
        "from": "dir-with-your-dlls",
        "filter": [
          "*.dll"
        ]
}`
