### ISSUE TITLE
not working on windows 10

### ISSUE THREAD

**Issue by abhishekgargg** [WilixLead/iohook#58]
## Expected Behavior

I should have been able to build iohook.
## Current Behavior

At the time of building the code, I'm getting an error "refresh_locale_list [628]: Could not find keyboard map for locale 0X000000000409"
## Possible Solution

iohook is using libuiohook, and this error is because of libuiohook, not iohook. However, this error is resolved in the libuiohook version 1.1 . I built iohook binaries using 1.1 version of libuiohook and was able to make it work in windows 10. Although, the error still persisted in node version of the binary, but the electron version of the binary worked superb on windows.
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): electron 1.8.3, node 8.4, abi 57, iohook 0.1.13
* Operating System and version (desktop or mobile): windows 10
* Link to your project:

**Comment by hrishabhkumar** [comment]
I am also facing same issue.

**Comment by skyrocker** [comment]
Hi @WilixLead,
Can you upload the updated binaries for windows?
I have been facing this issue as well for a really long time. Now that I know that it can be fixed, it'll be really helpful to get a working version for windows.

Please release a latest version as soon as possible.

**Comment by matthewshirley** [comment]
I'll take ownership on this issue... you can all expect a pull request soon. 🎉

I'm also going to address building on Windows without having to use mingw32.

**Comment by LiamKarlMitchell** [comment]
Got it built and copied over, but get a different error about failed to open key in registry.

```
refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 3 layouts.
refresh_locale_list [493]: Received 3 locales.
get_keyboard_layout_file [455]: RegOpenKeyEx failed to open key: "SYSTEM\CurrentControlSet\Control\Keyboard Layouts\00001409"!
refresh_locale_list [634]: Could not find keyboard map for locale 0000000004090409!
load_input_helper [866]: refresh_locale_list() found 2 locale(s).
```
