### ISSUE TITLE
Iohook can't run in MacOS

### ISSUE THREAD

**Issue by pihey12** [WilixLead/iohook#59]
## Expected Behavior

Can Run Iohook in macOS that not needed manually allow the apps from the security & privacy->Accessibility

## Current Behavior

when my app starts run, the iohook mouse events is not working . Then the macOS notified that the app needed to allow the apps from Security & Privacy->Accessibility. After I allowed and reopen the app, the iohook mouse event is start working again 

## Possible Solution

I explored that the MacOS thinks the Iohook some kind of keylogger thats why the Iohook will not run if it's not allowed from the security

## Context

Iohook will run in MacOS thats not needed to manually allow the app from the Security & Privacy->Accessibility.

## Your Environment

* Version used: 0.1.13
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node JS v8.10.0, Electron 1.8.4
* Operating System and version (desktop or mobile): MacOS 10.10.5

**Comment by WilixLead** [comment]
iohook not a keylogger like hack tool, so described behavior is normal for apps with iohook module.
