### ISSUE TITLE
Error: No available formula with the name "autoreconf"

### ISSUE THREAD

**Issue by stefvw93** [WilixLead/iohook#6]
brew install cmake autoreconf libtool pkg-config => doesn't work for me :( There's no available formula with the name autoreconf.

EDIT: This leads to the following error when installing iohook, using sudo npm i iohook:

info CMD BUILD
info RUN cmake --build "/Users/stef/Documents/dev/lolhelper/node_modules/iohook/build" --config Release
./bootstrap.sh: line 7: autoreconf: command not found
make[2]: *** [CMakeFiles/prepare_iuhook] Error 127
make[1]: *** [CMakeFiles/prepare_iuhook.dir/all] Error 2
make: *** [all] Error 2
ERR! OMG Process terminated: 2

**Comment by stefvw93** [comment]
I solved this by installing brew automake. You might want to inform developers about this in your readme! :)

$ brew install automake

**Comment by WilixLead** [comment]
Thank you for feedback. I update readme, some later I update it in npm package. 
Also, please give me any feedback if you will use this module. I just want to understand how it simple/difficult for developers or what is problems they have with using this module.
