### ISSUE TITLE
Implement 'shiftKey', 'metaKey', 'ctrlKey', 'altKey' properties to keyboard event

### ISSUE THREAD

**Issue by matthewshirley** [WilixLead/iohook#61]
Essentially mimic what a JS keyboard event contains: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/shiftKey

## Expected Behavior
Properties contain a boolean if the modifier key is pressed (true) or not (false). 

## Current Behavior
There is currently no properties that easily define if a modifier key was pressed.

**Comment by Djiit** [comment]
This is great. As a rule of thumb, we need to mimic the JS Keyboard API :)

**Comment by DCzajkowski** [comment]
I think it can be closed as of recent commits. 🙂
