### ISSUE TITLE
Iohook hook failed to enabled in Mac OS

### ISSUE THREAD

**Issue by superpihey** [WilixLead/iohook#66]
## Expected Behavior

Iohook module will run in the Mac OS without granting access from the Security & Privacy->Accessibility.

## Current Behavior

The Iohook event are not working.
Then on the terminal logs, it throws error like this: 

> hook_run [1342]: Accessibility API is disabled!
> hook_run [1350]: Something, something, something, complete.
> hook_enable [257]: Thread Result: (0X40).
> Failed to enable access for assistive devices. (0X40)
> 

## Possible Solution

Still unknown how to fix this.

## Steps to Reproduce (for bugs)

1.npm start
2.The electron app start to run with the iohook.
3.On the terminal, the error log will thrown about the hook_run.

## Context

I just want iohook can run that not needed manually grant access from Accessibility of MacOS

## Your Environment

* Version used: v.0.1.13
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v8.10.0, Electron 1.8.4
* Operating System and version (desktop or mobile): Mac OS v 10.10.5

**Comment by Djiit** [comment]
This is actually intended, and users only have to do this once. iohook is not a keylogger :(.

**Comment by superpihey** [comment]
@Djiit is there way to found out if the module is not working?
I just want my app close if the Iohook not successful run.

**Comment by Djiit** [comment]
Oh, that's a good question! I'm more of a JS guy but our man @matthewshirley could help here :)

**Comment by superpihey** [comment]
Thanks, I'm also searching the possible way to check it.

**Comment by matthewshirley** [comment]
I think the easiest way would be creating a method called getStatus() which will return the libuiohook status. Could you try this prototype implementation? https://github.com/matthewshirley/iohook/tree/expose-current-status

You will need to call `NodeAddonHook.getStatus()` somewhere in index.js'. Perhaps in the _handler() method:

```js
  _handler(msg) {
    console.log(NodeHookAddon.getStatus());
    
    if (this.active === false) {
      return;
    }
    ...
```

You should see 64 in the console indicating UIOHOOK_ERROR_AXAPI_DISABLED. You can find a list of errors here: https://github.com/kwhat/libuiohook/blob/1.1/include/uiohook.h

I can't test this because I'm struggling to get libuiohook to throw an error.

**Comment by superpihey** [comment]
oh thanks for this solution but idk how to create a getStatus()  method for NodeHookAddon.
I created new variable inside of constructor:
`this.checkerAPI = true`;

then I created new condition inside of _handler(msg) function. The 'msg' always display undefined if the Accessibility API is disabled on the Mac OS.
`if (msg === undefined){
     this.checkerAPI = false;
}`

and last I input this to my main js or other js that called the iohook module.
```
‘use strict’;
const ioHook     = require(‘iohook’);

var checkerAPI  = true;

ioHook.start(true);
setTimeout(function() {
    checkerAPI = ioHook.checkerAPI;
}, 500);
```

when the checkerAPI is false then the app will close. thanks for the idea you suggest Sir.

**Comment by jlsilva1994** [comment]
Hi there, i was digging on the libuiohook  and i found this method:

https://github.com/WilixLead/iohook/blob/cd1c5ae74c46d00e8739bee1dec66f58fb63e612/libuiohook/src/darwin/input_helper.c#L55

@matthewshirley maybe this method could help us no? how can we access it from the iohook index.js?

I'm also trying to check if the accessibility permission is enabled or not, and give feedback to the user with that information

Thanks for the great module btw 😄

**Comment by superpihey** [comment]
Hi there, I found this weird problem from macOS. Whenever I re change some code from a inner folder of my application file and open my electron application, the accessibility warning message pop ups even my application is still checked/grant access from the settings.
But when I redo my file to original and open my application, there's no message warning and iohook success to run.

is there way how to fix it?

**Comment by superpihey** [comment]
Wa, I found my solution on:

> the accessibility warning message keep pop ups even my application is still checked/grant access from the settings

I need to attach code signature for my electron application and use the auto updater so the bundle signature will not break. 😄

**Comment by Djiit** [comment]
Great ! I'm happy you found a solution. Closing this for now.

**Comment by delewis13** [comment]
@Djiit 

Thanks for this great library! 

As above, it would be awesome if there was some API to check accessibility status so that I might provide a notification to user that they need to enable.

Cheers :)

**Comment by marcelblum** [comment]
@delewis13 in Electron there is already a built in API for that see https://www.electronjs.org/docs/latest/api/system-preferences#systempreferencesistrustedaccessibilityclientprompt-macos

**Comment by delewis13** [comment]
@marcelblum *facepalm* - how have I not seen this before >< Thank you very much!

Regardless would still be awesome to see this in IOHook for other use-cases, but indeed the Electron API is enough for me!
