### ISSUE TITLE
[electron] iohook.node file not created for electron 

### ISSUE THREAD

**Issue by zxiang77** [WilixLead/iohook#67]
I added cmake-js to the package as instructed in the example but still cannot create the iohook.node file for electron. I feel current example for electron is not very clear. Could you give more explicit descriptions? Thanks!

## Your Environment

my package.json
```
  "devDependencies": {
    "electron": "^1.8.4",
    "electron-rebuild": "^1.4.0"
  },
  "dependencies": {
    "iohook": "^0.1.15",
    "jQuery": "^1.7.4",
    "materialize-css": "^1.0.0-beta"
  },
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.4.7"
  }
```
and I tried both mac and windows. It seems electron-rebuild is using node-gyp but you are using cmake-js. Idk that could be the problem.

**Comment by Djiit** [comment]
You have to set the `runtimeVerison` in `cmake-js` accordingly.

Here you have electron `1.8.4` and a declared runtime version of `1.4.7`

Try this : 
```json
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.8.4"
  }
```

**Comment by Djiit** [comment]
Hi there, do you have a correct "io-hook" dict in your `package.json` ? as in : 
```json
"iohook": {
  "targets": [
    "node-59",
    "electron-57"
  ],
  "platforms": [
    "win32",
    "darwin",
    "linux"
  ],
  "arches": [
    "x64",
    "ia32"
  ]
}
````

**Comment by zxiang77** [comment]
Yeah. Adding `iohook` dict in `package.json` solved my problem. Note: You have to add the field before `npm install iohook` because the installation process depends on that field. You can close this issue now. Thanks!

**Comment by Mat-thieu** [comment]
Thanks @zxiang77 the docs aren't clear enough on this (although it does make sense thinking about it).
