### ISSUE TITLE
Create prebuild environment

### ISSUE THREAD

**Issue by vespakoen** [WilixLead/iohook#7]
Hey man!

I see you are having issues with bundling the modules.
Just wanted to let you know that you can use https://github.com/mafintosh/prebuild for that

Cheers

**Comment by WilixLead** [comment]
Hello! 

Thank you! I think about prebuilds for this module, but 'prebuild' use node-gyp for build module.
It this case, we should use cmake because libuiohook developed in cmake.

**Comment by vespakoen** [comment]
Hey!

I see, it looks like the JavaScript API of "prebuild" allows you to specify a custom backend.
Apparently, cmake-js (which you already seem to be using) claims it works "exactly" like node-gyp, so I wonder if it could be "dropped in" perhaps?

I might give this a try myself when I have some time on my hands.

Thanks for making this!

**Comment by vespakoen** [comment]
I have put together this bindings.gyp file which seems to work with node-gyp.
Not really tested thoroughly but anyways:

```
{
  "targets": [
    {
      "target_name": "iohook",
      "sources": [ "src/iohook.cc" ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
        "libuiohook/include"
      ],
      "conditions": [
        [ 'OS!="win"', {
          "cflags+": [ "-std=c++14" ],
          "cflags_c+": [ "-std=c++14" ],
          "cflags_cc+": [ "-std=c++14" ],
        }],
        [ 'OS=="mac"', {
          "xcode_settings": {
            'GCC_ENABLE_CPP_RTTI': 'YES',
            'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
            'MACOSX_DEPLOYMENT_TARGET':'10.8',
            'CLANG_CXX_LIBRARY': 'libc++',
            'CLANG_CXX_LANGUAGE_STANDARD':'c++11',
            'GCC_VERSION': 'com.apple.compilers.llvm.clang.1_0'
          }
        }]
      ]
    }
  ]
}
```

Took a little from here: https://github.com/peteyy/native-addon-example/blob/cpp14/binding.gyp
Then from here to get rid of a compiler is deprecated warning on OSX: https://github.com/mapnik/node-mapnik/blob/c8dee11e7e8f29168cf4e96c46b13d4933246327/binding.gyp#L115-L120

Hope it helps

**Comment by vespakoen** [comment]
Ok never mind me that was super stupid, it's complaining about missing symbols of course since it needs a whole bunch more linked then "libuiohook/include" that I added up there.

Anyways, here was my previous try to get cmake working in the prebuild script:

```
var prebuild = require('prebuild')
// var cmake = require('cmake-js')
var cmake = require('node-cmake')
var nodeGyp = require('node-gyp')()
cmake.parseArgv = function (args) {
  nodeGyp.parseArgv(args)
  cmake.commands = nodeGyp.commands
  cmake.todo = nodeGyp.todo
}
var version = '0.8.0'
prebuild.build({
  log: {
    verbose: console.log.bind(console),
    error: console.log.bind(console)
  },
  pkg: require('./package.json'),
  gyp: cmake
}, version, function (err) {
  // ...
  console.log(err)
})
```

Not so great either as `node-cmake` and `cmake-js` are not fully compatible with node-gyp (see the parseArgv hack I did there)

Perhaps a little shell script that does what `prebuild` does is the way to go here...

**Comment by vespakoen** [comment]
Sorry for the spam, updated example that starts working better =)

```js
var prebuild = require('prebuild')
var spawn = require('child_process').spawn

var version = '6.10.0'
const run = (args) => {
  spawn('./node_modules/.bin/ncmake', args).stdout.pipe(process.stdout)
}
const cmakeWrap = {
  todo: [],
  parseArgv: function (argv) {
    console.log('PARSE ARGV', arguments)
    this.todo.push({
      name: argv[2],
      args: argv.slice(2)
    })
  },
  commands: {
    build: run,
    clean: run,
    configure: run,
    rebuild: run,
    update: run,
    install: run,
    list: run
  }
}

prebuild.build({
  log: {
    verbose: console.log.bind(console),
    error: console.log.bind(console)
  },
  pkg: require('./package.json'),
  gyp: cmakeWrap
}, version, function (err) {
  // ...
  console.log(err)
})
```

**Comment by vespakoen** [comment]
Updated version that seems to work for electron too (replaces `--target` flag with `--runtime-version` flag)

```js
var prebuild = require('prebuild/prebuild')
var upload = require('prebuild/upload')
var spawn = require('child_process').spawn
var async = require('async')
var extend = require('xtend')

const run = (args, cb) => {
  args = args.map(arg => {
    if (arg.indexOf('--target') > -1) {
      return arg.replace('--target', '--runtime-version')
    }
    return arg
  })
  const proc = spawn('./node_modules/.bin/cmake-js', args, { env: process.env })
  proc.stdout.pipe(process.stdout)
  proc.stderr.pipe(process.stderr)
  proc.on('exit', (code, sig) => {
    if (code === 1) {
      return cb(new Error(`Failed with signal: ${sig}`))
    }
    cb()
  })
}

const cmakeWrap = {
  todo: [],
  parseArgv: function (argv) {
    this.todo.push({
      name: argv[2],
      args: argv.slice(2)
    })
  },
  commands: {
    build: run,
    clean: run,
    configure: run,
    rebuild: run,
    update: run,
    install: run,
    list: run
  }
}

var opts = {
  target: process.versions.node,
  runtime: 'node',
  arch: process.arch,
  libc: process.env.LIBC,
  platform: process.platform,
  all: false,
  force: false,
  debug: false,
  verbose: false,
  path: '.',
  log: {
    verbose: console.log.bind(console),
    error: console.log.bind(console)
  },
  pkg: require('./package.json'),
  gyp: cmakeWrap,
  prebuild: require('node-abi').supportedTargets,
}
console.log(opts.prebuild)

var files = []
async.eachSeries(opts.prebuild, function (target, next) {
  prebuild(opts, target.target, target.runtime, function (err, tarGz) {
    if (err) return next(err)
    files.push(tarGz)
    next()
  })
}, function (err) {
  if (err) return onbuilderror(err)
  uploadFiles(files)
})

function uploadFiles (files) {
  console.log('Uploading ' + files.length + ' prebuilds(s) to Github releases')
  upload(extend(opts, {files: files}), function (err, result) {
    if (err) return onbuilderror(err)
    console.log('Found ' + result.old.length + ' prebuild(s) on Github')
    if (result.old.length) {
      result.old.forEach(function (build) {
        console.log('-> ' + build)
      })
    }
    console.log('Uploaded ' + result.new.length + ' new prebuild(s) to Github')
    if (result.new.length) {
      result.new.forEach(function (build) {
        console.log('-> ' + build)
      })
    }
  })
}

function onbuilderror (err) {
  if (!err) return
  console.error(err)
  process.exit(2)
}
```

You could use appveyor to build windows "prebuilds": https://www.appveyor.com/
Config which is similar to what we would need: https://github.com/Level/leveldown/blob/master/appveyor.yml

```
☁  iohook [master] ⚡ ls -lah prebuilds
drwxr-xr-x  15 koen  staff   510B Mar 22 00:44 .
drwxr-xr-x  19 koen  staff   646B Mar 22 00:44 ..
-rw-r--r--   1 koen  staff    23K Mar 22 00:42 iohook-v0.1.2-electron-v47-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:42 iohook-v0.1.2-electron-v48-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:43 iohook-v0.1.2-electron-v49-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:43 iohook-v0.1.2-electron-v50-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:44 iohook-v0.1.2-electron-v51-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:44 iohook-v0.1.2-electron-v53-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:03 iohook-v0.1.2-node-v11-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:03 iohook-v0.1.2-node-v14-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:04 iohook-v0.1.2-node-v46-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:04 iohook-v0.1.2-node-v47-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:04 iohook-v0.1.2-node-v48-darwin-x64.tar.gz
-rw-r--r--   1 koen  staff    23K Mar 22 00:04 iohook-v0.1.2-node-v51-darwin-x64.tar.gz
```

**Comment by vespakoen** [comment]
I have been trying out appveyor on my fork: https://github.com/vespakoen/iohook
It runs the build script, but I guess the CMakeFile needs some love for Windows still?

https://ci.appveyor.com/project/vespakoen/iohook

**Comment by WilixLead** [comment]
Hello! looks like you do big work today :)
But I already have build system in project and it not require any additional modules like prebuild.
All what need, setup target and run "npm run compile". Also, module already support automatic selection of prebuilds.
Problem not in building prebuild packages, how to store all needed versions? 
In your case, you got 6 electron builds and 6 node builds, but it all only for darwin.
Module should support other linux/windows platforms, and it takes 
6(versions) * 3(electron/node/nw.js) * 3(darwin/linux/windows) = 54(prebuild versions)

I can't place all versions in one package. Best way, store all versions in CDN and download it for each installation. I just don't know free CDNs for implementing this.

If you can help with it, I will be happy implement prebuild system in this module. I want to do it long time

**Comment by vespakoen** [comment]
Hey WilixLead!

That's great news =)

Fortunately, the builds are pretty small (23K each it seems).

The github releases would be your "free CDN", if you make a git tag, you can later upload files to it on github, or using their API (which is what the "prebuild" script does)

https://github.com/vespakoen/iohook/blob/master/build.js#L87

"prebuild-install" can easily install the .tar.gz's from the github releases for users installing your package (replacing the install.js script)

I was hoping to setup AppVeyor to produce (& "github release") the windows versions for us (x86 & x64)

cmake-js also claims that the builds it produces are "NW.js" compatible out of the box
```
NW.js: all CMake.js based native modules are compatible with NW.js out-of-the-box, there is no nw-gyp like magic required
```
Can you point me to the code that handles "module already support automatic selection of prebuilds." ?

I have tried compiling it with Visual Studio Code (the libuiohook github somewhere says it should work) but I haven't had any luck with it, I must also add that my C++ / Windows skills are near non-existant haha)

There is also jNativeHook which also uses libuiohook and uses Msys2 to compile it:
https://github.com/kwhat/jnativehook/wiki/Compiling

Which is what I was going to try next, but I guess I will wait for your response first this time =)

**Comment by vespakoen** [comment]
I just has success building libuiohook on windows using msys2, but this is not helping us in any way, we really need to get CMake working for it to produce the .node library, I haven't succeeded in this though so would love to hear you experiences. I also found https://github.com/ayoubserti/node-iohook, which also has a appveyor.yml conf, so I got excited for a second but noticed their builds are failing as well.

So I guess my question is, you claim to have been able to install this package on a windows machine using cmake-js, if this is the case, can you describe the steps you took / tools you used?

If I can get it working myself I'd be glad to help you automatically get those builds up on github / help you setup the prebuild-install script.

**Comment by ayoubserti** [comment]
@vespakoen  The time I added appveyor hook for continue integration, Appveyor didn't support VS2013 and use a fixed CMake version.

@WilixLead  Thank you for picking my code and continue working. I didn't really find time to fix all known issues. I think I deserve a credit on your module ;)

**Comment by vespakoen** [comment]
I bit the bullet and installed the VS Build tools / CMake in a Windows 10 VM and finally was able to compile it myself by using a whopping combination of tools (node / git / msys2 / autoconf / pkg-utils etc).

I have tried out a bunch of configurations but the missing config.h / config.h.in, generated through the `./autogen.sh` / `./configure` was the missing link to get it to compile.

So I went and found this thing on the internet: https://github.com/schismtracker/schismtracker/blob/master/appveyor.yml

And modified it to our needs here: https://github.com/vespakoen/iohook/blob/master/appveyor.yml

The `-Dsnprintf=_snprintf` option that is added for certain VS versions seems to be incorrect, I had to remove that to make it work on VS2015 in my Windows 10 (64 bit) VM.

The compilation on AppVeyor with VS 2013 succeeded to build `libuiohook` (!!), but has a couple of issues with `iohook.cc` still https://ci.appveyor.com/project/vespakoen/iohook/build/61/job/0jbyavfnfi5gb2ji

I will now see how well it works on `node-iohook`.

Since both of you guys are here now, can we merge these 2 packages? if so / into which one / can I be a contributor?

**Comment by vespakoen** [comment]
I think you are going to like this...

https://github.com/vespakoen/iohook/releases/tag/v0.1.3

![bitmoji](https://render.bitstrips.com/v2/cpanel/10214286-131555433_1-s4-v1.png?transparent=1&width=246)

Now checking if they actually work... ;)

**Comment by vespakoen** [comment]
Just build them on my OSX machine, and published a version to NPM to test it out, first test when installing it on my mac works:

```
  testing  npm install --save iohook-prebuild-test

> iohook-prebuild-test@0.1.3 install /Users/koen/Projects/testing/node_modules/iohook-prebuild-test
> prebuild-install

prebuild-install info begin Prebuild-install version 2.1.1
prebuild-install info looking for local prebuild @ prebuilds/iohook-prebuild-test-v0.1.3-node-v48-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/koen/.npm/_prebuilds/https-github.com-vespakoen-iohook-releases-download-v0.1.3-iohook-prebuild-test-v0.1.3-node-v48-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/vespakoen/iohook/releases/download/v0.1.3/iohook-prebuild-test-v0.1.3-node-v48-darwin-x64.tar.gz
prebuild-install http 200 https://github.com/vespakoen/iohook/releases/download/v0.1.3/iohook-prebuild-test-v0.1.3-node-v48-darwin-x64.tar.gz
prebuild-install info downloading to @ /Users/koen/.npm/_prebuilds/https-github.com-vespakoen-iohook-releases-download-v0.1.3-iohook-prebuild-test-v0.1.3-node-v48-darwin-x64.tar.gz.80561-f813d97878fef.tmp
prebuild-install info renaming to @ /Users/koen/.npm/_prebuilds/https-github.com-vespakoen-iohook-releases-download-v0.1.3-iohook-prebuild-test-v0.1.3-node-v48-darwin-x64.tar.gz
prebuild-install info unpacking @ /Users/koen/.npm/_prebuilds/https-github.com-vespakoen-iohook-releases-download-v0.1.3-iohook-prebuild-test-v0.1.3-node-v48-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/koen/Projects/testing/node_modules/iohook-prebuild-test/build/Release/iohook.node
prebuild-install info unpack required /Users/koen/Projects/testing/node_modules/iohook-prebuild-test/build/Release/iohook.node successfully
prebuild-install info install Prebuild successfully installed!
testing@1.0.0 /Users/koen/Projects/testing
└─┬ iohook-prebuild-test@0.1.3
  ├── bindings@1.2.1
  └─┬ prebuild-install@2.1.1
    ├── expand-template@1.0.3
    ├── github-from-package@0.0.0
    ├── minimist@1.2.0
    ├── node-abi@2.0.0
    ├── noop-logger@0.1.1
    ├─┬ npmlog@4.0.2
    │ ├─┬ are-we-there-yet@1.1.2
    │ │ ├── delegates@1.0.0
    │ │ └─┬ readable-stream@2.2.6
    │ │   ├── buffer-shims@1.0.0
    │ │   ├── core-util-is@1.0.2
    │ │   ├── inherits@2.0.3
    │ │   ├── isarray@1.0.0
    │ │   ├── process-nextick-args@1.0.7
    │ │   ├── string_decoder@0.10.31
    │ │   └── util-deprecate@1.0.2
    │ ├── console-control-strings@1.1.0
    │ ├─┬ gauge@2.7.3
    │ │ ├── aproba@1.1.1
    │ │ ├── has-unicode@2.0.1
    │ │ ├── object-assign@4.1.1
    │ │ ├── signal-exit@3.0.2
    │ │ ├─┬ string-width@1.0.2
    │ │ │ ├── code-point-at@1.1.0
    │ │ │ └─┬ is-fullwidth-code-point@1.0.0
    │ │ │   └── number-is-nan@1.0.1
    │ │ ├─┬ strip-ansi@3.0.1
    │ │ │ └── ansi-regex@2.1.1
    │ │ └── wide-align@1.1.0
    │ └── set-blocking@2.0.0
    ├── os-homedir@1.0.2
    ├─┬ pump@1.0.2
    │ ├── end-of-stream@1.4.0
    │ └─┬ once@1.4.0
    │   └── wrappy@1.0.2
    ├─┬ rc@1.1.7
    │ ├── deep-extend@0.4.1
    │ ├── ini@1.3.4
    │ └── strip-json-comments@2.0.1
    ├─┬ simple-get@1.4.3
    │ └── unzip-response@1.0.2
    ├─┬ tar-fs@1.15.2
    │ ├── chownr@1.0.1
    │ ├─┬ mkdirp@0.5.1
    │ │ └── minimist@0.0.8
    │ └─┬ tar-stream@1.5.2
    │   └── bl@1.2.0
    ├── tunnel-agent@0.4.3
    └── xtend@4.0.1

npm WARN testing@1.0.0 No description
npm WARN testing@1.0.0 No repository field.
☁  testing  nano index.js
☁  testing  node index.js
{ button: 0, clicks: 0, x: 664, y: 676, type: 'mousemove' }
{ button: 0, clicks: 0, x: 658, y: 679, type: 'mousemove' }
{ button: 0, clicks: 0, x: 652, y: 682, type: 'mousemove' }
{ button: 0, clicks: 0, x: 648, y: 685, type: 'mousemove' }
{ button: 0, clicks: 0, x: 642, y: 688, type: 'mousemove' }
```

**Comment by WilixLead** [comment]
Wow. How many information :)  Sorry, I just will be busy this days.
I can't approve your pull request, it contains changes in packages.json, like 
"name": "iohook-prebuild-test"

And why you change "class" to vars? And other es5/6 const/lets and etc?

**Comment by vespakoen** [comment]
I changed some stuff to ES5 to make it work in older environments.
I also might have sprinkled some const / lets in there since I mostly write ES6 these days and I guess it has become a habit.

I know the pull is not ready to go, I had to change the package name to be able to publish it to npm for example, the "prebuild-install" package determines the git releases url from the git url in the package json, not the regular one, but the one that NPM adds when you install a package trought it (basically, "npm link" or "npm install git+https://github.com/vespakoen/my-fork-of-your-thing.git" didn't work.

Also there are waaay to many commits from testing out the windows build on AppVeyor (triggering builds through commits)

Anyways, I tested some of the built packages on OSX and Windows and NW.js, they all worked!

(see my fork's the releases page for all the builds I created: https://github.com/vespakoen/iohook/releases)

I did the OSX builds on my own machine, the windows builds on AppVeyor, no linux builds yet (could probably be automated through travis)

Funny thing is, I was trying to use this project for a (Adobe) After Effects extension, which uses NW.js, turns out it doesn't support native extensions, so now I made a new CMakeLists.txt file that builds one of libuiohook's examples into a binary, and I added jsoncpp in there to log things I need to json (If you are interested in the code, I can share), now I simply start my binary as a subprocess and parse the json it outputs on stdout.

I also got rid of using "node-abi" and other weird hacks to get a list of all versions / platforms / abi's (what a mess it is actually!)

and hand crafted a list in "support.js" (https://github.com/vespakoen/iohook/blob/228b5d56942370061a196d79a7eba2af4e242787/support.js)

Hope you can figure it out a bit and take it from here, but I'll be happy to help / answer questions.

**Comment by WilixLead** [comment]
@vespakoen Great work! I make manual merge your commits in local machine.
Build and upload works great in MacOS! Cool!
Now I try build linux on ubuntu and after that, try to use your AppVeyor config. I think it will works too.

But, I keep my ES6 style (classes and const/let). It works on older node.js versions and I think we no need support more older then v4.x where it work only with --harmony flag

Great job! After testing I upload all to repo and npm

**Comment by vespakoen** [comment]
Cool man, as you wish! Enjoy!

**Comment by WilixLead** [comment]
Hello! Sorry for long silent. I be in vocation 🇲🇽 🌮  :)
Now I continue updating module. I made some small fixes, but your job is great. Now I try configure travis-ci and appveior for automatic build publish on push.
Also I plain keep compilation if build is not found. I think it helps to other peoples use this module in specific versions of node/electron/etc..

**Comment by WilixLead** [comment]
Ok. I push new version with released prebuild system. Still need some updates for support more environments like io.js/nw.js and some older versions of node.js
