### ISSUE TITLE
iohook\iohook-master\builds\node-v57-win32-ia32\build\Release\iohook.node is not a valid Win32 application

### ISSUE THREAD

**Issue by lixinxiaobai** [WilixLead/iohook#70]
## Current Behavior
```
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: \\?\D:\xx\iohook\iohook-master\builds\node-v57-win32-ia32\build\Release\iohook.node is not a valid Win32 application\\?\D:\xx\iohook\iohook-master\builds\node-v57-win32-ia32\build\Release\iohook.node
```

I installed it and did not complain
`npm install`
`npm run build`

## Your Environment

* Version used: 0.1.15
* Environment name and version: nodejs 8.9.3  32bit
* Operating System and version: windows10 64bit

**Comment by Djiit** [comment]
Hi there ! We're happy to help :)

Could you please use the template we provide for the issue ? i.e. What are you trying to do ? How did you install the package ? (from npm ? from this repository ?)

Thanks!

**Comment by matthewshirley** [comment]
iohook.node is:
- actually a 64-bit module
- 32-bit module, but it's linking to a 64-bit module

Perhaps CMake or Visual Studio is installed as a 64-bit causing it compile a 64 bit binary (instead of 32bit)?

**Comment by farezramilo** [comment]
I'm having the same issue with @jesperjohansson.

**Comment by dai875939260** [comment]
I'm having the same issue too

**Comment by fateleak** [comment]
same issue for MacOS

**Comment by Nubuck** [comment]
I was getting the same error while running an electron app on a Windows 7 32 bit machine with the ia32 target, same as @lixinxiaobai 

I setup a true 32bit Windows enviroment to rebuild the iohook native addons and subsequently the electron app and happily shipped today.

I believe @matthewshirley is correct in saying that the ia32 prebuilds currently published were infact 64bit wrapped in 32bit somehow.
My electron app had other native addon dependencies, namely [active-win](https://github.com/sindresorhus/active-win) which required an electron-rebuild on the 32bit environment.

I have pushed the ia32 builds for node and electron ABI 57 to this [repo](https://github.com/Nubuck/iohook-prebuild-v57-win32-ia32) - as those I can confirm work. I did add a readme with links to the tools used and steps followed to create these builds.

For now, as a workaround in my electron app, I store these builds in the project and replace the addon files downloaded by yarn for iohook in a postbuild script.

Hopefully the builds in the repo work for the guys having issues and help figure out the root issue on the published ia32 windows builds.

**Comment by Djiit** [comment]
Hi there, closing this as we now have theses binaries.

**Comment by aizaku** [comment]
I am running into the same issue with "node-64", "electron-64"..
Please help

**Comment by Djiit** [comment]
Hi @aizaku , could you please open a new issue with your problem ? Thanks !

**Comment by tbs-arpit** [comment]
@Nubuck It works perfectly. Thanks you so much.
