### ISSUE TITLE
iohook/src/iohook.h:3:17: fatal error: nan.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by bychok300** [WilixLead/iohook#72]
i tryed to build manualy but it failed with: 
config.status: executing depfiles commands
config.status: executing libtool commands
[  0%] Built target prepare_iuhook
[ 75%] Built target uiohook
[ 87%] Building CXX object CMakeFiles/iohook.dir/src/iohook.cc.o
In file included from /home/rem0tec0de/iohook/src/iohook.cc:1:0:
/home/rem0tec0de/iohook/src/iohook.h:3:17: fatal error: nan.h: No such file or directory
compilation terminated.
CMakeFiles/iohook.dir/build.make:62: recipe for target 'CMakeFiles/iohook.dir/src/iohook.cc.o' failed
make[2]: *** [CMakeFiles/iohook.dir/src/iohook.cc.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/iohook.dir/all' failed
make[1]: *** [CMakeFiles/iohook.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bychok300** [comment]
Seems that i was need a nan module. `npm -g install nan`

**Comment by Djiit** [comment]
Hi there ! Just a word about that : prior to building iohook, you should have run `npm install` in the iohook dir to fetch the dependencies (`nan`and `segfault-handler`)
