### ISSUE TITLE
keyup and key down doesn't return key character

### ISSUE THREAD

**Issue by bychok300** [WilixLead/iohook#73]
i use basic example with keyup parametr and it returns to me `{ keycode: 30, rawcode: 97, type: 'keyup' }`, without key character. But in readme declared template of console output `{keychar: 'f', keycode: 19, rawcode: 15, type: 'keypress'}`. What i do wrong?
P.S. where i can see the table `character:his number`? I googling for js keycodes but it seems different that keycodes in iohook

**Comment by Djiit** [comment]
Hi there ! We're happy to help :). Could you please use the template we provide for issues ? Thanks !

**Comment by bychok300** [comment]
#54 it a solution, but will it functionality built in?
