### ISSUE TITLE
[Mac OS] Manual build

### ISSUE THREAD

**Issue by DCzajkowski** [WilixLead/iohook#78]
Hello everyone! I have a question regarding manual builds of iohook.
What I did, is:
- made a fork of the repo
- cloned it locally
- made changes in the `src/iohook.cc` and in `index.js`
- `brew install cmake automake libtool pkg-config`
- `npm run build`
- `cd examples`
- `node example.js`

My changes in `index.js` are reflected, although my C `src/iohook.cc` program doesn't seem to be used. Even after commenting whole file, builds succeed. How do you compile the `src/iohook.cc` and use it in the package?

### OS
- Mac OS 10.12.6

Checked on:
- Node v8.3.0 & NPM 5.6.0

**Comment by DCzajkowski** [comment]
Ok, it seems like the `npm run build` is not really building anything, despite it saying:
> [100%] Built target iohook

During the build I get:
> aclocal: warning: couldn't open directory '/opt/local/share/aclocal': No such file or directory

Will investigate!

**Comment by DCzajkowski** [comment]
In `libuiohook/bootstrap.sh` there is this:
```
if [ "$(uname)" == "Darwin" ]; then
    include=" -I/opt/local/share/aclocal"
fi
```

It makes aclocal to search in a non-existant directory. After creating that directory manually, error goes away, but still nothing is built.

**Comment by DCzajkowski** [comment]
I have updated my Node version to v10.1.0 and NPM to 6.0.1. Now the simple `npm i` fails. Seems like you require a package that requires full Xcode app :/ I'll try to install it and see what happens

**Comment by DCzajkowski** [comment]
Actually, scratch that. Xcode now requires macOS version 10.13.2 or later _sigh_

**Comment by DCzajkowski** [comment]
I've asked my friend to build the files on his Mac (since he has full xcode), but it seems like nothing is built (ie. changes in the `.cc` file are not reflected after `npm run build` nor `npm run deploy`). :/

**Comment by DCzajkowski** [comment]
It seems like new Node version has its issues when xcode is not present. We have finally resolved it on my friend's computer. A PR to the documentation is coming.

**Comment by Djiit** [comment]
For the record, Node 10 deployment is quite a disaster as it breaks many, many things.
E.g. the segfault-handler dependency uses a deprecated import and breaks iohook on Node 10 on some platform.

**Comment by DCzajkowski** [comment]
What fixed it for me was actally downgrading Node to 8.3 😂
