### ISSUE TITLE
[Question] How does using libuiohook with GPL, result with MIT License?

### ISSUE THREAD

**Issue by steamypassion** [WilixLead/iohook#86]
As title. Any example in real life case, how it iohook be licensed as MIT?
Is it similar mean any significant expert with domain knowledge can wrapped a GPL Library for new use because there is no change to the GPL code? 
Sorry not really familiar much with legal term.

**Comment by DCzajkowski** [comment]
https://softwareengineering.stackexchange.com/questions/316393/what-to-do-when-using-mit-licensed-code-in-a-gpl-licensed-project

**Comment by steamypassion** [comment]
It is an awesome project. It is best there is clean room implementation of libuiohook if there is chance of someone contribute incentive, Feel free to close the ticket, It almost answer the question or can start a discussion.
