### ISSUE TITLE
keycode is 0 on Windows 10

### ISSUE THREAD

**Issue by DanielRuf** [WilixLead/iohook#90]
`keycode` is `0` on Windows 10, affects all keys.

**Comment by DanielRuf** [comment]
I'm using the pure Node.js solution on Windows 10 with Node.js 10 and try to fetch the `keypress` event.

**Comment by DanielRuf** [comment]
Installed it in a fresh project yesterday.

**Comment by zxiang77** [comment]
Have you tried to modify your `package.json` such as mentioned in https://github.com/WilixLead/iohook/issues/67 ?

**Comment by DanielRuf** [comment]
I do not use Electrin in any way so I'm wondering how this can be relevant for me.

**Comment by zxiang77** [comment]
I was wondering if you have added
`
"iohook": {
  "targets": [
    "node-59",
    "electron-57"
  ],
  "platforms": [
    "win32",
    "darwin",
    "linux"
  ],
  "arches": [
    "x64",
    "ia32"
  ]
}
`
to your `package.json`. You have add this before install iohook. But since you can load the AddOn, this might not be relevant...

**Comment by DanielRuf** [comment]
This is just for node-gyp. So far it works so this is not needed, only a normal `npm i iohook`.

**Comment by Djiit** [comment]
Hi there! thanks for you report :).

Could you tell us a bit more ? You can use the issue template we provide or, at least, tell us about your OS and Node.js version.

If you have a spare 5minutes, you could also wire-up a small projet so we can reproduce the bug easily.

**Comment by Djiit** [comment]
Any news on this ? I'm closing this issue, but feel free to ping me if you have anymore information.
